// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_fruit_ninja_apprentice = "CgkI-Yyo2bodEAIQFA"; // <GPGSID>
        public const string achievement_combo_prodigy = "CgkI-Yyo2bodEAIQFg"; // <GPGSID>
        public const string achievement_fruit_extravaganza = "CgkI-Yyo2bodEAIQGQ"; // <GPGSID>
        public const string achievement_combo_virtuoso = "CgkI-Yyo2bodEAIQGA"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkI-Yyo2bodEAIQCw"; // <GPGSID>
        public const string achievement_fruit_ninja_legend = "CgkI-Yyo2bodEAIQGg"; // <GPGSID>
        public const string achievement_fruit_salad = "CgkI-Yyo2bodEAIQDg"; // <GPGSID>
        public const string achievement_tasty_quadro = "CgkI-Yyo2bodEAIQDw"; // <GPGSID>
        public const string achievement_orange_blitz = "CgkI-Yyo2bodEAIQFQ"; // <GPGSID>
        public const string achievement_fruit_ninja_master = "CgkI-Yyo2bodEAIQFw"; // <GPGSID>
        public const string achievement_juicy_start = "CgkI-Yyo2bodEAIQDA"; // <GPGSID>
        public const string achievement_fruit_novice = "CgkI-Yyo2bodEAIQDQ"; // <GPGSID>
        public const string achievement_slice_master = "CgkI-Yyo2bodEAIQEw"; // <GPGSID>
        public const string achievement_berry_fan = "CgkI-Yyo2bodEAIQEQ"; // <GPGSID>
        public const string achievement_pulp_fiction = "CgkI-Yyo2bodEAIQEg"; // <GPGSID>
        public const string achievement_combo_beginner = "CgkI-Yyo2bodEAIQEA"; // <GPGSID>

}

